INSERT INTO TankLog (tank_id, water_level, time_stamp) values('OHT001',(SELECT capacity from tank where tank_id='OHT001'),NOW());
INSERT INTO TankLog (tank_id, water_level, time_stamp) values('OHT002',(SELECT capacity from tank where tank_id='OHT002'),NOW());
INSERT INTO TankLog (tank_id, water_level, time_stamp) values('OHT003',(SELECT capacity from tank where tank_id='OHT003'),NOW());
INSERT INTO TankLog (tank_id, water_level, time_stamp) values('OHT004',(SELECT capacity from tank where tank_id='OHT004'),NOW());
INSERT INTO TankLog (tank_id, water_level, time_stamp) values('OHT005',(SELECT capacity from tank where tank_id='OHT005'),NOW());
INSERT INTO TankLog (tank_id, water_level, time_stamp) values('OHT006',(SELECT capacity from tank where tank_id='OHT006'),NOW());
INSERT INTO TankLog (tank_id, water_level, time_stamp) values('OHT007',(SELECT capacity from tank where tank_id='OHT007'),NOW());
INSERT INTO TankLog (tank_id, water_level, time_stamp) values('OHT008',(SELECT capacity from tank where tank_id='OHT008'),NOW());
INSERT INTO TankLog (tank_id, water_level, time_stamp) values('OHT009',(SELECT capacity from tank where tank_id='OHT009'),NOW());
INSERT INTO TankLog (tank_id, water_level, time_stamp) values('OHT010',(SELECT capacity from tank where tank_id='OHT010'),NOW());
INSERT INTO TankLog (tank_id, water_level, time_stamp) values('OHT011',(SELECT capacity from tank where tank_id='OHT011'),NOW());
INSERT INTO TankLog (tank_id, water_level, time_stamp) values('OHT012',(SELECT capacity from tank where tank_id='OHT012'),NOW());
INSERT INTO TankLog (tank_id, water_level, time_stamp) values('OHT013',(SELECT capacity from tank where tank_id='OHT013'),NOW());
INSERT INTO TankLog (tank_id, water_level, time_stamp) values('OHT014',(SELECT capacity from tank where tank_id='OHT014'),NOW());
INSERT INTO TankLog (tank_id, water_level, time_stamp) values('OHT015',(SELECT capacity from tank where tank_id='OHT015'),NOW());
INSERT INTO TankLog (tank_id, water_level, time_stamp) values('OHT016',(SELECT capacity from tank where tank_id='OHT016'),NOW());
INSERT INTO TankLog (tank_id, water_level, time_stamp) values('OHT017',(SELECT capacity from tank where tank_id='OHT017'),NOW());
INSERT INTO TankLog (tank_id, water_level, time_stamp) values('OHT018',(SELECT capacity from tank where tank_id='OHT018'),NOW());
INSERT INTO TankLog (tank_id, water_level, time_stamp) values('OHT019',(SELECT capacity from tank where tank_id='OHT019'),NOW());
INSERT INTO TankLog (tank_id, water_level, time_stamp) values('OHT020',(SELECT capacity from tank where tank_id='OHT020'),NOW());
INSERT INTO TankLog (tank_id, water_level, time_stamp) values('OHT021',(SELECT capacity from tank where tank_id='OHT021'),NOW());
INSERT INTO TankLog (tank_id, water_level, time_stamp) values('OHT022',(SELECT capacity from tank where tank_id='OHT022'),NOW());
INSERT INTO TankLog (tank_id, water_level, time_stamp) values('OHT023',(SELECT capacity from tank where tank_id='OHT023'),NOW());
INSERT INTO TankLog (tank_id, water_level, time_stamp) values('OHT024',(SELECT capacity from tank where tank_id='OHT024'),NOW());
INSERT INTO TankLog (tank_id, water_level, time_stamp) values('OHT025',(SELECT capacity from tank where tank_id='OHT025'),NOW());
INSERT INTO TankLog (tank_id, water_level, time_stamp) values('OHT026',(SELECT capacity from tank where tank_id='OHT026'),NOW());
INSERT INTO TankLog (tank_id, water_level, time_stamp) values('OHT027',(SELECT capacity from tank where tank_id='OHT027'),NOW());
INSERT INTO TankLog (tank_id, water_level, time_stamp) values('OHT028',(SELECT capacity from tank where tank_id='OHT028'),NOW());
INSERT INTO TankLog (tank_id, water_level, time_stamp) values('OHT029',(SELECT capacity from tank where tank_id='OHT029'),NOW());
INSERT INTO TankLog (tank_id, water_level, time_stamp) values('OHT030',(SELECT capacity from tank where tank_id='OHT030'),NOW());
INSERT INTO TankLog (tank_id, water_level, time_stamp) values('OHT031',(SELECT capacity from tank where tank_id='OHT031'),NOW());
INSERT INTO TankLog (tank_id, water_level, time_stamp) values('OHT032',(SELECT capacity from tank where tank_id='OHT032'),NOW());
INSERT INTO TankLog (tank_id, water_level, time_stamp) values('OHT033',(SELECT capacity from tank where tank_id='OHT033'),NOW());
INSERT INTO TankLog (tank_id, water_level, time_stamp) values('OHT034',(SELECT capacity from tank where tank_id='OHT034'),NOW());
INSERT INTO TankLog (tank_id, water_level, time_stamp) values('OHT035',(SELECT capacity from tank where tank_id='OHT035'),NOW());
INSERT INTO TankLog (tank_id, water_level, time_stamp) values('OHT036',(SELECT capacity from tank where tank_id='OHT036'),NOW());
INSERT INTO TankLog (tank_id, water_level, time_stamp) values('OHT037',(SELECT capacity from tank where tank_id='OHT037'),NOW());
INSERT INTO TankLog (tank_id, water_level, time_stamp) values('OHT038',(SELECT capacity from tank where tank_id='OHT038'),NOW());
INSERT INTO TankLog (tank_id, water_level, time_stamp) values('OHT039',(SELECT capacity from tank where tank_id='OHT039'),NOW());
INSERT INTO TankLog (tank_id, water_level, time_stamp) values('OHT040',(SELECT capacity from tank where tank_id='OHT040'),NOW());
INSERT INTO TankLog (tank_id, water_level, time_stamp) values('OHT041',(SELECT capacity from tank where tank_id='OHT041'),NOW());
INSERT INTO TankLog (tank_id, water_level, time_stamp) values('OHT042',(SELECT capacity from tank where tank_id='OHT042'),NOW());
INSERT INTO TankLog (tank_id, water_level, time_stamp) values('OHT043',(SELECT capacity from tank where tank_id='OHT043'),NOW());
INSERT INTO TankLog (tank_id, water_level, time_stamp) values('OHT044',(SELECT capacity from tank where tank_id='OHT044'),NOW());
INSERT INTO TankLog (tank_id, water_level, time_stamp) values('OHT045',(SELECT capacity from tank where tank_id='OHT045'),NOW());
INSERT INTO TankLog (tank_id, water_level, time_stamp) values('OHT046',(SELECT capacity from tank where tank_id='OHT046'),NOW());
INSERT INTO TankLog (tank_id, water_level, time_stamp) values('OHT047',(SELECT capacity from tank where tank_id='OHT047'),NOW());
INSERT INTO TankLog (tank_id, water_level, time_stamp) values('OHT048',(SELECT capacity from tank where tank_id='OHT048'),NOW());
INSERT INTO TankLog (tank_id, water_level, time_stamp) values('OHT049',(SELECT capacity from tank where tank_id='OHT049'),NOW());
INSERT INTO TankLog (tank_id, water_level, time_stamp) values('OHT050',(SELECT capacity from tank where tank_id='OHT050'),NOW());
INSERT INTO TankLog (tank_id, water_level, time_stamp) values('OHT051',(SELECT capacity from tank where tank_id='OHT051'),NOW());
INSERT INTO TankLog (tank_id, water_level, time_stamp) values('OHT052',(SELECT capacity from tank where tank_id='OHT052'),NOW());
INSERT INTO TankLog (tank_id, water_level, time_stamp) values('OHT053',(SELECT capacity from tank where tank_id='OHT053'),NOW());
INSERT INTO TankLog (tank_id, water_level, time_stamp) values('OHT054',(SELECT capacity from tank where tank_id='OHT054'),NOW());
INSERT INTO TankLog (tank_id, water_level, time_stamp) values('OHT055',(SELECT capacity from tank where tank_id='OHT055'),NOW());
INSERT INTO TankLog (tank_id, water_level, time_stamp) values('OHT056',(SELECT capacity from tank where tank_id='OHT056'),NOW());
INSERT INTO TankLog (tank_id, water_level, time_stamp) values('OHT057',(SELECT capacity from tank where tank_id='OHT057'),NOW());
INSERT INTO TankLog (tank_id, water_level, time_stamp) values('OHT058',(SELECT capacity from tank where tank_id='OHT058'),NOW());
INSERT INTO TankLog (tank_id, water_level, time_stamp) values('OHT059',(SELECT capacity from tank where tank_id='OHT059'),NOW());
INSERT INTO TankLog (tank_id, water_level, time_stamp) values('OHT060',(SELECT capacity from tank where tank_id='OHT060'),NOW());
INSERT INTO TankLog (tank_id, water_level, time_stamp) values('OHT061',(SELECT capacity from tank where tank_id='OHT061'),NOW());
INSERT INTO TankLog (tank_id, water_level, time_stamp) values('OHT062',(SELECT capacity from tank where tank_id='OHT062'),NOW());
INSERT INTO TankLog (tank_id, water_level, time_stamp) values('OHT063',(SELECT capacity from tank where tank_id='OHT063'),NOW());
INSERT INTO TankLog (tank_id, water_level, time_stamp) values('OHT064',(SELECT capacity from tank where tank_id='OHT064'),NOW());
INSERT INTO TankLog (tank_id, water_level, time_stamp) values('OHT065',(SELECT capacity from tank where tank_id='OHT065'),NOW());
INSERT INTO TankLog (tank_id, water_level, time_stamp) values('OHT066',(SELECT capacity from tank where tank_id='OHT066'),NOW());
INSERT INTO TankLog (tank_id, water_level, time_stamp) values('OHT067',(SELECT capacity from tank where tank_id='OHT067'),NOW());
INSERT INTO TankLog (tank_id, water_level, time_stamp) values('OHT068',(SELECT capacity from tank where tank_id='OHT068'),NOW());
INSERT INTO TankLog (tank_id, water_level, time_stamp) values('OHT069',(SELECT capacity from tank where tank_id='OHT069'),NOW());
INSERT INTO TankLog (tank_id, water_level, time_stamp) values('OHT070',(SELECT capacity from tank where tank_id='OHT070'),NOW());
INSERT INTO TankLog (tank_id, water_level, time_stamp) values('OHT071',(SELECT capacity from tank where tank_id='OHT071'),NOW());




INSERT INTO PumpLog (pump_id, status, time_stamp) values('WPS001',TRUE,'2024-04-22 11:30:00');
INSERT INTO PumpLog (pump_id, status, time_stamp) values('WPS002',TRUE,'2024-04-22 11:30:00');
INSERT INTO PumpLog (pump_id, status, time_stamp) values('WPS003',TRUE,'2024-04-22 11:30:00');
INSERT INTO PumpLog (pump_id, status, time_stamp) values('WPS004',TRUE,'2024-04-22 11:30:00');
INSERT INTO PumpLog (pump_id, status, time_stamp) values('WPS005',TRUE,'2024-04-22 11:30:00');
INSERT INTO PumpLog (pump_id, status, time_stamp) values('WPS006',TRUE,'2024-04-22 11:30:00');
INSERT INTO PumpLog (pump_id, status, time_stamp) values('WPS007',TRUE,'2024-04-22 11:30:00');
INSERT INTO PumpLog (pump_id, status, time_stamp) values('WPS008',TRUE,'2024-04-22 11:30:00');
INSERT INTO PumpLog (pump_id, status, time_stamp) values('WPS009',TRUE,'2024-04-22 11:30:00');
INSERT INTO PumpLog (pump_id, status, time_stamp) values('WPS010',TRUE,'2024-04-22 11:30:00');
INSERT INTO PumpLog (pump_id, status, time_stamp) values('WPS011',TRUE,'2024-04-22 11:30:00');
INSERT INTO PumpLog (pump_id, status, time_stamp) values('WPS012',TRUE,'2024-04-22 11:30:00');
INSERT INTO PumpLog (pump_id, status, time_stamp) values('WPS013',TRUE,'2024-04-22 11:30:00');
INSERT INTO PumpLog (pump_id, status, time_stamp) values('WPS014',TRUE,'2024-04-22 11:30:00');
INSERT INTO PumpLog (pump_id, status, time_stamp) values('WPS015',TRUE,'2024-04-22 11:30:00');
INSERT INTO PumpLog (pump_id, status, time_stamp) values('WPS016',TRUE,'2024-04-22 11:30:00');
INSERT INTO PumpLog (pump_id, status, time_stamp) values('WPS017',TRUE,'2024-04-22 11:30:00');
INSERT INTO PumpLog (pump_id, status, time_stamp) values('WPS018',TRUE,'2024-04-22 11:30:00');
INSERT INTO PumpLog (pump_id, status, time_stamp) values('WPS019',TRUE,'2024-04-22 11:30:00');
INSERT INTO PumpLog (pump_id, status, time_stamp) values('WPS020',TRUE,'2024-04-22 11:30:00');
INSERT INTO PumpLog (pump_id, status, time_stamp) values('WPS021',TRUE,'2024-04-22 11:30:00');
INSERT INTO PumpLog (pump_id, status, time_stamp) values('WPS022',TRUE,'2024-04-22 11:30:00');
INSERT INTO PumpLog (pump_id, status, time_stamp) values('WPS023',TRUE,'2024-04-22 11:30:00');
INSERT INTO PumpLog (pump_id, status, time_stamp) values('WPS024',TRUE,'2024-04-22 11:30:00');
INSERT INTO PumpLog (pump_id, status, time_stamp) values('WPS025',TRUE,'2024-04-22 11:30:00');
INSERT INTO PumpLog (pump_id, status, time_stamp) values('WPS026',TRUE,'2024-04-22 11:30:00');
INSERT INTO PumpLog (pump_id, status, time_stamp) values('WPS027',TRUE,'2024-04-22 11:30:00');
INSERT INTO PumpLog (pump_id, status, time_stamp) values('WPS028',TRUE,'2024-04-22 11:30:00');
INSERT INTO PumpLog (pump_id, status, time_stamp) values('WPS029',TRUE,'2024-04-22 11:30:00');
INSERT INTO PumpLog (pump_id, status, time_stamp) values('WPS030',TRUE,'2024-04-22 11:30:00');
INSERT INTO PumpLog (pump_id, status, time_stamp) values('WPS031',TRUE,'2024-04-22 11:30:00');
INSERT INTO PumpLog (pump_id, status, time_stamp) values('WPS032',TRUE,'2024-04-22 11:30:00');
INSERT INTO PumpLog (pump_id, status, time_stamp) values('WPS033',TRUE,'2024-04-22 11:30:00');
INSERT INTO PumpLog (pump_id, status, time_stamp) values('WPS034',TRUE,'2024-04-22 11:30:00');
INSERT INTO PumpLog (pump_id, status, time_stamp) values('WPS035',TRUE,'2024-04-22 11:30:00');
INSERT INTO PumpLog (pump_id, status, time_stamp) values('WPS036',TRUE,'2024-04-22 11:30:00');
INSERT INTO PumpLog (pump_id, status, time_stamp) values('WPS037',TRUE,'2024-04-22 11:30:00');
INSERT INTO PumpLog (pump_id, status, time_stamp) values('WPS038',TRUE,'2024-04-22 11:30:00');
INSERT INTO PumpLog (pump_id, status, time_stamp) values('WPS039',TRUE,'2024-04-22 11:30:00');
INSERT INTO PumpLog (pump_id, status, time_stamp) values('WPS040',TRUE,'2024-04-22 11:30:00');
INSERT INTO PumpLog (pump_id, status, time_stamp) values('WPS041',TRUE,'2024-04-22 11:30:00');
INSERT INTO PumpLog (pump_id, status, time_stamp) values('WPS042',TRUE,'2024-04-22 11:30:00');
INSERT INTO PumpLog (pump_id, status, time_stamp) values('WPS043',TRUE,'2024-04-22 11:30:00');
INSERT INTO PumpLog (pump_id, status, time_stamp) values('WPS044',TRUE,'2024-04-22 11:30:00');
INSERT INTO PumpLog (pump_id, status, time_stamp) values('WPS045',TRUE,'2024-04-22 11:30:00');
INSERT INTO PumpLog (pump_id, status, time_stamp) values('WPS046',TRUE,'2024-04-22 11:30:00');
INSERT INTO PumpLog (pump_id, status, time_stamp) values('WPS047',TRUE,'2024-04-22 11:30:00');
INSERT INTO PumpLog (pump_id, status, time_stamp) values('WPS048',TRUE,'2024-04-22 11:30:00');
INSERT INTO PumpLog (pump_id, status, time_stamp) values('WPS049',TRUE,'2024-04-22 11:30:00');
INSERT INTO PumpLog (pump_id, status, time_stamp) values('WPS050',TRUE,'2024-04-22 11:30:00');
INSERT INTO PumpLog (pump_id, status, time_stamp) values('WPS051',TRUE,'2024-04-22 11:30:00');
INSERT INTO PumpLog (pump_id, status, time_stamp) values('WPS052',TRUE,'2024-04-22 11:30:00');
INSERT INTO PumpLog (pump_id, status, time_stamp) values('WPS053',TRUE,'2024-04-22 11:30:00');
INSERT INTO PumpLog (pump_id, status, time_stamp) values('WPS065',TRUE,'2024-04-22 11:30:00');
INSERT INTO PumpLog (pump_id, status, time_stamp) values('WPS055',TRUE,'2024-04-22 11:30:00');
INSERT INTO PumpLog (pump_id, status, time_stamp) values('WPS056',TRUE,'2024-04-22 11:30:00');
INSERT INTO PumpLog (pump_id, status, time_stamp) values('WPS057',TRUE,'2024-04-22 11:30:00');
INSERT INTO PumpLog (pump_id, status, time_stamp) values('WPS058',TRUE,'2024-04-22 11:30:00');
INSERT INTO PumpLog (pump_id, status, time_stamp) values('WPS066',TRUE,'2024-04-22 11:30:00');
INSERT INTO PumpLog (pump_id, status, time_stamp) values('WPS067',TRUE,'2024-04-22 11:30:00');
INSERT INTO PumpLog (pump_id, status, time_stamp) values('WPS061',TRUE,'2024-04-22 11:30:00');
INSERT INTO PumpLog (pump_id, status, time_stamp) values('WPS062',TRUE,'2024-04-22 11:30:00');
INSERT INTO PumpLog (pump_id, status, time_stamp) values('WPS063',TRUE,'2024-04-22 11:30:00');
INSERT INTO PumpLog (pump_id, status, time_stamp) values('WPS064',TRUE,'2024-04-22 11:30:00');
INSERT INTO PumpLog (pump_id, status, time_stamp) values('WPS001',FALSE,'2024-04-22 19:30:00');
INSERT INTO PumpLog (pump_id, status, time_stamp) values('WPS002',FALSE,'2024-04-22 19:30:00');
INSERT INTO PumpLog (pump_id, status, time_stamp) values('WPS003',FALSE,'2024-04-22 19:30:00');
INSERT INTO PumpLog (pump_id, status, time_stamp) values('WPS004',FALSE,'2024-04-22 19:30:00');
INSERT INTO PumpLog (pump_id, status, time_stamp) values('WPS005',FALSE,'2024-04-22 19:30:00');
INSERT INTO PumpLog (pump_id, status, time_stamp) values('WPS006',FALSE,'2024-04-22 19:30:00');
INSERT INTO PumpLog (pump_id, status, time_stamp) values('WPS007',FALSE,'2024-04-22 19:30:00');
INSERT INTO PumpLog (pump_id, status, time_stamp) values('WPS008',FALSE,'2024-04-22 19:30:00');
INSERT INTO PumpLog (pump_id, status, time_stamp) values('WPS009',FALSE,'2024-04-22 19:30:00');
INSERT INTO PumpLog (pump_id, status, time_stamp) values('WPS010',FALSE,'2024-04-22 19:30:00');
INSERT INTO PumpLog (pump_id, status, time_stamp) values('WPS011',FALSE,'2024-04-22 19:30:00');
INSERT INTO PumpLog (pump_id, status, time_stamp) values('WPS012',FALSE,'2024-04-22 19:30:00');
INSERT INTO PumpLog (pump_id, status, time_stamp) values('WPS013',FALSE,'2024-04-22 19:30:00');
INSERT INTO PumpLog (pump_id, status, time_stamp) values('WPS014',FALSE,'2024-04-22 19:30:00');
INSERT INTO PumpLog (pump_id, status, time_stamp) values('WPS015',FALSE,'2024-04-22 19:30:00');
INSERT INTO PumpLog (pump_id, status, time_stamp) values('WPS016',FALSE,'2024-04-22 19:30:00');
INSERT INTO PumpLog (pump_id, status, time_stamp) values('WPS017',FALSE,'2024-04-22 19:30:00');
INSERT INTO PumpLog (pump_id, status, time_stamp) values('WPS018',FALSE,'2024-04-22 19:30:00');
INSERT INTO PumpLog (pump_id, status, time_stamp) values('WPS019',FALSE,'2024-04-22 19:30:00');
INSERT INTO PumpLog (pump_id, status, time_stamp) values('WPS020',FALSE,'2024-04-22 19:30:00');
INSERT INTO PumpLog (pump_id, status, time_stamp) values('WPS021',FALSE,'2024-04-22 19:30:00');
INSERT INTO PumpLog (pump_id, status, time_stamp) values('WPS022',FALSE,'2024-04-22 19:30:00');
INSERT INTO PumpLog (pump_id, status, time_stamp) values('WPS023',FALSE,'2024-04-22 19:30:00');
INSERT INTO PumpLog (pump_id, status, time_stamp) values('WPS024',FALSE,'2024-04-22 19:30:00');
INSERT INTO PumpLog (pump_id, status, time_stamp) values('WPS025',FALSE,'2024-04-22 19:30:00');
INSERT INTO PumpLog (pump_id, status, time_stamp) values('WPS026',FALSE,'2024-04-22 19:30:00');
INSERT INTO PumpLog (pump_id, status, time_stamp) values('WPS027',FALSE,'2024-04-22 19:30:00');
INSERT INTO PumpLog (pump_id, status, time_stamp) values('WPS028',FALSE,'2024-04-22 19:30:00');
INSERT INTO PumpLog (pump_id, status, time_stamp) values('WPS029',FALSE,'2024-04-22 19:30:00');
INSERT INTO PumpLog (pump_id, status, time_stamp) values('WPS030',FALSE,'2024-04-22 19:30:00');
INSERT INTO PumpLog (pump_id, status, time_stamp) values('WPS031',FALSE,'2024-04-22 19:30:00');
INSERT INTO PumpLog (pump_id, status, time_stamp) values('WPS032',FALSE,'2024-04-22 19:30:00');
INSERT INTO PumpLog (pump_id, status, time_stamp) values('WPS033',FALSE,'2024-04-22 19:30:00');
INSERT INTO PumpLog (pump_id, status, time_stamp) values('WPS034',FALSE,'2024-04-22 19:30:00');
INSERT INTO PumpLog (pump_id, status, time_stamp) values('WPS035',FALSE,'2024-04-22 19:30:00');
INSERT INTO PumpLog (pump_id, status, time_stamp) values('WPS036',FALSE,'2024-04-22 19:30:00');
INSERT INTO PumpLog (pump_id, status, time_stamp) values('WPS037',FALSE,'2024-04-22 19:30:00');
INSERT INTO PumpLog (pump_id, status, time_stamp) values('WPS038',FALSE,'2024-04-22 19:30:00');
INSERT INTO PumpLog (pump_id, status, time_stamp) values('WPS039',FALSE,'2024-04-22 19:30:00');
INSERT INTO PumpLog (pump_id, status, time_stamp) values('WPS040',FALSE,'2024-04-22 19:30:00');
INSERT INTO PumpLog (pump_id, status, time_stamp) values('WPS041',FALSE,'2024-04-22 19:30:00');
INSERT INTO PumpLog (pump_id, status, time_stamp) values('WPS042',FALSE,'2024-04-22 19:30:00');
INSERT INTO PumpLog (pump_id, status, time_stamp) values('WPS043',FALSE,'2024-04-22 19:30:00');
INSERT INTO PumpLog (pump_id, status, time_stamp) values('WPS044',FALSE,'2024-04-22 19:30:00');
INSERT INTO PumpLog (pump_id, status, time_stamp) values('WPS045',FALSE,'2024-04-22 19:30:00');
INSERT INTO PumpLog (pump_id, status, time_stamp) values('WPS046',FALSE,'2024-04-22 19:30:00');
INSERT INTO PumpLog (pump_id, status, time_stamp) values('WPS047',FALSE,'2024-04-22 19:30:00');
INSERT INTO PumpLog (pump_id, status, time_stamp) values('WPS048',FALSE,'2024-04-22 19:30:00');
INSERT INTO PumpLog (pump_id, status, time_stamp) values('WPS049',FALSE,'2024-04-22 19:30:00');
INSERT INTO PumpLog (pump_id, status, time_stamp) values('WPS050',FALSE,'2024-04-22 19:30:00');
INSERT INTO PumpLog (pump_id, status, time_stamp) values('WPS051',FALSE,'2024-04-22 19:30:00');
INSERT INTO PumpLog (pump_id, status, time_stamp) values('WPS052',FALSE,'2024-04-22 19:30:00');
INSERT INTO PumpLog (pump_id, status, time_stamp) values('WPS053',FALSE,'2024-04-22 19:30:00');
INSERT INTO PumpLog (pump_id, status, time_stamp) values('WPS065',FALSE,'2024-04-22 19:30:00');
INSERT INTO PumpLog (pump_id, status, time_stamp) values('WPS055',FALSE,'2024-04-22 19:30:00');
INSERT INTO PumpLog (pump_id, status, time_stamp) values('WPS056',FALSE,'2024-04-22 19:30:00');
INSERT INTO PumpLog (pump_id, status, time_stamp) values('WPS057',FALSE,'2024-04-22 19:30:00');
INSERT INTO PumpLog (pump_id, status, time_stamp) values('WPS058',FALSE,'2024-04-22 19:30:00');
INSERT INTO PumpLog (pump_id, status, time_stamp) values('WPS066',FALSE,'2024-04-22 19:30:00');
INSERT INTO PumpLog (pump_id, status, time_stamp) values('WPS067',FALSE,'2024-04-22 19:30:00');
INSERT INTO PumpLog (pump_id, status, time_stamp) values('WPS061',FALSE,'2024-04-22 19:30:00');
INSERT INTO PumpLog (pump_id, status, time_stamp) values('WPS062',FALSE,'2024-04-22 19:30:00');
INSERT INTO PumpLog (pump_id, status, time_stamp) values('WPS063',FALSE,'2024-04-22 19:30:00');
INSERT INTO PumpLog (pump_id, status, time_stamp) values('WPS064',FALSE,'2024-04-22 19:30:00');



INSERT INTO ReservLog (reserv_id, water_level, time_stamp) values('CWR001',(SELECT capacity from reservoir where reserv_id='CWR001'),NOW());
INSERT INTO ReservLog (reserv_id, water_level, time_stamp) values('CWR002',(SELECT capacity from reservoir where reserv_id='CWR002'),NOW());
INSERT INTO ReservLog (reserv_id, water_level, time_stamp) values('CWR003',(SELECT capacity from reservoir where reserv_id='CWR003'),NOW());
INSERT INTO ReservLog (reserv_id, water_level, time_stamp) values('CWR004',(SELECT capacity from reservoir where reserv_id='CWR004'),NOW());
INSERT INTO ReservLog (reserv_id, water_level, time_stamp) values('CWR005',(SELECT capacity from reservoir where reserv_id='CWR005'),NOW());
INSERT INTO ReservLog (reserv_id, water_level, time_stamp) values('CWR006',(SELECT capacity from reservoir where reserv_id='CWR006'),NOW());
INSERT INTO ReservLog (reserv_id, water_level, time_stamp) values('CWR007',(SELECT capacity from reservoir where reserv_id='CWR007'),NOW());
INSERT INTO ReservLog (reserv_id, water_level, time_stamp) values('CWR008',(SELECT capacity from reservoir where reserv_id='CWR008'),NOW());
INSERT INTO ReservLog (reserv_id, water_level, time_stamp) values('CWR009',(SELECT capacity from reservoir where reserv_id='CWR009'),NOW());
INSERT INTO ReservLog (reserv_id, water_level, time_stamp) values('CWR010',(SELECT capacity from reservoir where reserv_id='CWR010'),NOW());
INSERT INTO ReservLog (reserv_id, water_level, time_stamp) values('CWR011',(SELECT capacity from reservoir where reserv_id='CWR011'),NOW());
INSERT INTO ReservLog (reserv_id, water_level, time_stamp) values('CWR012',(SELECT capacity from reservoir where reserv_id='CWR012'),NOW());
INSERT INTO ReservLog (reserv_id, water_level, time_stamp) values('CWR013',(SELECT capacity from reservoir where reserv_id='CWR013'),NOW());
INSERT INTO ReservLog (reserv_id, water_level, time_stamp) values('CWR014',(SELECT capacity from reservoir where reserv_id='CWR014'),NOW());
INSERT INTO ReservLog (reserv_id, water_level, time_stamp) values('CWR015',(SELECT capacity from reservoir where reserv_id='CWR015'),NOW());
INSERT INTO ReservLog (reserv_id, water_level, time_stamp) values('CWR016',(SELECT capacity from reservoir where reserv_id='CWR016'),NOW());
INSERT INTO ReservLog (reserv_id, water_level, time_stamp) values('CWR017',(SELECT capacity from reservoir where reserv_id='CWR017'),NOW());
INSERT INTO ReservLog (reserv_id, water_level, time_stamp) values('CWR018',(SELECT capacity from reservoir where reserv_id='CWR018'),NOW());
INSERT INTO ReservLog (reserv_id, water_level, time_stamp) values('CWR019',(SELECT capacity from reservoir where reserv_id='CWR019'),NOW());
INSERT INTO ReservLog (reserv_id, water_level, time_stamp) values('CWR020',(SELECT capacity from reservoir where reserv_id='CWR020'),NOW());
INSERT INTO ReservLog (reserv_id, water_level, time_stamp) values('CWR021',(SELECT capacity from reservoir where reserv_id='CWR021'),NOW());
INSERT INTO ReservLog (reserv_id, water_level, time_stamp) values('CWR022',(SELECT capacity from reservoir where reserv_id='CWR022'),NOW());
INSERT INTO ReservLog (reserv_id, water_level, time_stamp) values('CWR023',(SELECT capacity from reservoir where reserv_id='CWR023'),NOW());
INSERT INTO ReservLog (reserv_id, water_level, time_stamp) values('CWR024',(SELECT capacity from reservoir where reserv_id='CWR024'),NOW());
INSERT INTO ReservLog (reserv_id, water_level, time_stamp) values('CWR025',(SELECT capacity from reservoir where reserv_id='CWR025'),NOW());
INSERT INTO ReservLog (reserv_id, water_level, time_stamp) values('CWR026',(SELECT capacity from reservoir where reserv_id='CWR026'),NOW());
INSERT INTO ReservLog (reserv_id, water_level, time_stamp) values('CWR027',(SELECT capacity from reservoir where reserv_id='CWR027'),NOW());
INSERT INTO ReservLog (reserv_id, water_level, time_stamp) values('CWR028',(SELECT capacity from reservoir where reserv_id='CWR028'),NOW());
INSERT INTO ReservLog (reserv_id, water_level, time_stamp) values('CWR029',(SELECT capacity from reservoir where reserv_id='CWR029'),NOW());
INSERT INTO ReservLog (reserv_id, water_level, time_stamp) values('CWR030',(SELECT capacity from reservoir where reserv_id='CWR030'),NOW());
INSERT INTO ReservLog (reserv_id, water_level, time_stamp) values('CWR031',(SELECT capacity from reservoir where reserv_id='CWR031'),NOW());
INSERT INTO ReservLog (reserv_id, water_level, time_stamp) values('CWR032',(SELECT capacity from reservoir where reserv_id='CWR032'),NOW());
INSERT INTO ReservLog (reserv_id, water_level, time_stamp) values('CWR033',(SELECT capacity from reservoir where reserv_id='CWR033'),NOW());
INSERT INTO ReservLog (reserv_id, water_level, time_stamp) values('CWR034',(SELECT capacity from reservoir where reserv_id='CWR034'),NOW());
INSERT INTO ReservLog (reserv_id, water_level, time_stamp) values('CWR035',(SELECT capacity from reservoir where reserv_id='CWR035'),NOW());
INSERT INTO ReservLog (reserv_id, water_level, time_stamp) values('CWR036',(SELECT capacity from reservoir where reserv_id='CWR036'),NOW());
INSERT INTO ReservLog (reserv_id, water_level, time_stamp) values('CWR037',(SELECT capacity from reservoir where reserv_id='CWR037'),NOW());
INSERT INTO ReservLog (reserv_id, water_level, time_stamp) values('CWR038',(SELECT capacity from reservoir where reserv_id='CWR038'),NOW());
INSERT INTO ReservLog (reserv_id, water_level, time_stamp) values('CWR039',(SELECT capacity from reservoir where reserv_id='CWR039'),NOW());
INSERT INTO ReservLog (reserv_id, water_level, time_stamp) values('CWR040',(SELECT capacity from reservoir where reserv_id='CWR040'),NOW());
INSERT INTO ReservLog (reserv_id, water_level, time_stamp) values('CWR041',(SELECT capacity from reservoir where reserv_id='CWR041'),NOW());
INSERT INTO ReservLog (reserv_id, water_level, time_stamp) values('CWR042',(SELECT capacity from reservoir where reserv_id='CWR042'),NOW());
INSERT INTO ReservLog (reserv_id, water_level, time_stamp) values('CWR043',(SELECT capacity from reservoir where reserv_id='CWR043'),NOW());
INSERT INTO ReservLog (reserv_id, water_level, time_stamp) values('CWR044',(SELECT capacity from reservoir where reserv_id='CWR044'),NOW());
INSERT INTO ReservLog (reserv_id, water_level, time_stamp) values('CWR045',(SELECT capacity from reservoir where reserv_id='CWR045'),NOW());
INSERT INTO ReservLog (reserv_id, water_level, time_stamp) values('CWR046',(SELECT capacity from reservoir where reserv_id='CWR046'),NOW());
INSERT INTO ReservLog (reserv_id, water_level, time_stamp) values('CWR047',(SELECT capacity from reservoir where reserv_id='CWR047'),NOW());
INSERT INTO ReservLog (reserv_id, water_level, time_stamp) values('CWR048',(SELECT capacity from reservoir where reserv_id='CWR048'),NOW());
INSERT INTO ReservLog (reserv_id, water_level, time_stamp) values('CWR049',(SELECT capacity from reservoir where reserv_id='CWR049'),NOW());
INSERT INTO ReservLog (reserv_id, water_level, time_stamp) values('CWR050',(SELECT capacity from reservoir where reserv_id='CWR050'),NOW());
INSERT INTO ReservLog (reserv_id, water_level, time_stamp) values('CWR051',(SELECT capacity from reservoir where reserv_id='CWR051'),NOW());
INSERT INTO ReservLog (reserv_id, water_level, time_stamp) values('CWR052',(SELECT capacity from reservoir where reserv_id='CWR052'),NOW());
INSERT INTO ReservLog (reserv_id, water_level, time_stamp) values('CWR053',(SELECT capacity from reservoir where reserv_id='CWR053'),NOW());
INSERT INTO ReservLog (reserv_id, water_level, time_stamp) values('CWR054',(SELECT capacity from reservoir where reserv_id='CWR054'),NOW());
INSERT INTO ReservLog (reserv_id, water_level, time_stamp) values('CWR055',(SELECT capacity from reservoir where reserv_id='CWR055'),NOW());
INSERT INTO ReservLog (reserv_id, water_level, time_stamp) values('CWR056',(SELECT capacity from reservoir where reserv_id='CWR056'),NOW());
INSERT INTO ReservLog (reserv_id, water_level, time_stamp) values('CWR057',(SELECT capacity from reservoir where reserv_id='CWR057'),NOW());
INSERT INTO ReservLog (reserv_id, water_level, time_stamp) values('CWR058',(SELECT capacity from reservoir where reserv_id='CWR058'),NOW());
INSERT INTO ReservLog (reserv_id, water_level, time_stamp) values('CWR059',(SELECT capacity from reservoir where reserv_id='CWR059'),NOW());
INSERT INTO ReservLog (reserv_id, water_level, time_stamp) values('CWR060',(SELECT capacity from reservoir where reserv_id='CWR060'),NOW());
INSERT INTO ReservLog (reserv_id, water_level, time_stamp) values('CWR061',(SELECT capacity from reservoir where reserv_id='CWR061'),NOW());
INSERT INTO ReservLog (reserv_id, water_level, time_stamp) values('CWR062',(SELECT capacity from reservoir where reserv_id='CWR062'),NOW());
INSERT INTO ReservLog (reserv_id, water_level, time_stamp) values('CWR063',(SELECT capacity from reservoir where reserv_id='CWR063'),NOW());
INSERT INTO ReservLog (reserv_id, water_level, time_stamp) values('CWR064',(SELECT capacity from reservoir where reserv_id='CWR064'),NOW());
INSERT INTO ReservLog (reserv_id, water_level, time_stamp) values('CWR065',(SELECT capacity from reservoir where reserv_id='CWR065'),NOW());
INSERT INTO ReservLog (reserv_id, water_level, time_stamp) values('CWR066',(SELECT capacity from reservoir where reserv_id='CWR066'),NOW());